= Spring HATEOAS Examples

image:https://jenkins.spring.io/buildStatus/icon?job=spring-hateoas-examples%2Fmaster&subject=master[link=https://jenkins.spring.io/view/SpringHATEOAS/job/spring-hateoas-examples/]
image:https://jenkins.spring.io/buildStatus/icon?job=spring-hateoas-examples%2F0.x&subject=0.x[link=https://jenkins.spring.io/view/SpringHATEOAS/job/spring-hateoas-examples/]

This repository contains example projects to interact with Spring HATEOAS.

* Learn how to interact with a Spring HATEOAS-powered app, from inside as well as the command line.
* See how to upgrade a REST resource without having to create new media types, version URIs, etc.

We have separate folders for each of these:

== Spring HATEOAS Modules

* link:basics[Basics] - Poke and prod at a hypermedia-powered service from inside the code as well as externally using standard tools
* link:simplified[Simplified] - Use Spring HATEOAS in the simplest way possible.
* link:api-evolution[API Evolution] - Upgrade an existing REST resource
* link:hypermedia[Hypermedia] - Create hypermedia-driven REST resources, linking them together, and supporting older links.
* link:affordances[Affordances] - Create richer hypermedia controls using more complex hypermedia formats

NOTE: The master branch tracks Spring HATEOAS 1.0, based upon Spring Boot 2 + Spring Framework 5.
To see examples depicted against the 0.x branch (Spring 4.x) visit the https://github.com/spring-projects/spring-hateoas-examples/tree/0.x[0.x branch].

=== Making a release

1. Create a new release (on the main branch).
+
----
% ci/create-release.sh <release version> <next snapshot version>
----
+
2. With the release tagged, push the tagged version to the release branch.
+
----
% git checkout -b release
% git reset --hard <tag>
% git push -f origin release
----

NOTE: You can chain the previous set of commands together using `&&`.

The pipeline will build and release the "release" branch. It will also build a new a new snapshot and stage it on artifactory.
